In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from collections import namedtuple

import torch_geometric 
import torch_geometric.nn as geom_nn
#import torch_geometric.data as geom_data

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4497/4166561706.py", line 6, in <cell line: 6>
    import torch_geometric
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 317, in executing
    args = executing_cache[key]
KeyError: (<code object run_code at 0x7f6c16885920, file "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3333>, 140102211229984, 74)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 799, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 854, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 565, in stack_data
    yield from collapse_repeated(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/utils.py", line 84, in collapse_repeated
    yield from map(mapper, original_group)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 555, in mapper
    return cls(f, options)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 520, in __init__
    self.executing = Source.executing(frame_or_tb)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 369, in executing
    args = find(source=cls.for_frame(frame), retry_cache=True)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 252, in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 270, in for_filename
    result = source_cache[filename] = cls._for_filename_and_lines(filename, lines)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 281, in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 81, in __init__
    self.asttokens()
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 413, in asttokens
    return ASTTokens(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/asttokens.py", line 65, in __init__
    self.mark_tokens(self._tree)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/asttokens.py", line 76, in mark_tokens
    MarkTokens(self).visit_tree(root_node)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 47, in visit_tree
    util.visit_tree(node, self._visit_before_children, self._visit_after_children)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/util.py", line 192, in visit_tree
    ret = postvisit(current, par_value, value)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 90, in _visit_after_children
    nfirst, nlast = self._methods.get(self, node.__class__)(node, first, last)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 268, in visit_keyword
    util.expect_token(name, token.NAME, node.arg)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/util.py", line 56, in expect_token
    raise ValueError("Expected token %s, got %s on line %s col %s" % (
ValueError: Expected token NAME:'help', got NAME:'ast_transformers' on line 253 col 5

In [8]:
!ls

mc_25k.pkl  trk_processed_25k.pkl  Untitled.ipynb

In [2]:
mc = pd.read_pickle('mc_25k.pkl')
trk = pd.read_pickle('trk_processed_25k.pkl')

In [23]:
mc.index.max()[0]

24999

In [9]:
mc

                pv_L1reco_z0  pv_L1reco_sum     pv_MC
entry subentry
0     0             5.026911      79.777252  5.055163
1     0            -2.021080      90.041313 -3.608661
2     0            -0.141508     202.421341 -0.261453
3     0             2.744174     303.983124  2.803285
4     0            -1.279072     218.012939 -1.400667
...                      ...            ...       ...
24995 0            -0.085255      96.097534 -0.142578
24996 0            -1.918857     204.352753 -1.878616
24997 0             8.179408     304.295990  8.174589
24998 0            -4.635422     168.583572 -4.748836
24999 0             2.394885     417.355530  2.354877

[25000 rows x 3 columns]

In [13]:
trk = pd.read_pickle('trk_processed_25k.pkl')
trk['unique_trk_id'] = range(len(trk))

In [17]:
trk

                  trk_pt   trk_eta   trk_phi  trk_d0    trk_z0  trk_fake  \
entry subentry
0     0         2.623967  1.301414 -0.289234   999.0 -0.878906         2
      1         3.435026  0.566814 -0.159267   999.0  3.339844         2
      2         3.774908  1.815973 -0.240375   999.0  4.921875         1
      3         2.641448 -1.435747 -0.128747   999.0 -0.468750         2
      4         2.320653  1.837421  0.032604   999.0  4.980469         1
...                  ...       ...       ...     ...       ...       ...
24999 194       2.807081 -2.373757 -0.638281   999.0 -0.058594         2
      195       2.472056 -2.244333 -0.792948   999.0  6.328125         2
      196       2.391643 -2.093290 -0.658689   999.0 -0.410156         2
      197       6.140490  2.403961 -0.539389   999.0 -7.441406         2
      198       5.962409 -2.311289 -0.428627   999.0  1.640625         2

                is_pv  unique_trk_id
entry subentry
0     0             0              0
      1             0              1
      2             1              2
      3             0              3
      4             1              4
...               ...            ...
24999 194           0        4562531
      195           0        4562532
      196           0        4562533
      197           0        4562534
      198           0        4562535

[4562536 rows x 8 columns]

In [34]:
e0 = trk.xs(0, level='entry', drop_level=False)

In [35]:
e0

                  trk_pt   trk_eta   trk_phi  trk_d0    trk_z0  trk_fake  \
entry subentry
0     0         2.623967  1.301414 -0.289234   999.0 -0.878906         2
      1         3.435026  0.566814 -0.159267   999.0  3.339844         2
      2         3.774908  1.815973 -0.240375   999.0  4.921875         1
      3         2.641448 -1.435747 -0.128747   999.0 -0.468750         2
      4         2.320653  1.837421  0.032604   999.0  4.980469         1
...                  ...       ...       ...     ...       ...       ...
      154       2.026653 -2.021094 -1.062191   999.0 -0.410156         2
      155       2.049097 -2.055119 -0.964472   999.0 -0.410156         2
      156       2.222179 -2.426809 -0.693084   999.0  5.566406         2
      157       2.563973  2.081842 -0.530004   999.0 -3.046875         2
      158       2.303798  1.335547 -0.274176   999.0  4.804688         2

                is_pv  unique_trk_id
entry subentry
0     0             0              0
      1             0              1
      2             1              2
      3             0              3
      4             1              4
...               ...            ...
      154           0            154
      155           0            155
      156           0            156
      157           0            157
      158           0            158

[159 rows x 8 columns]

In [21]:
e0['unique_trk_id'].reset_index()

     entry  subentry  unique_trk_id
0        0         0              0
1        0         1              1
2        0         2              2
3        0         3              3
4        0         4              4
..     ...       ...            ...
154      0       154            154
155      0       155            155
156      0       156            156
157      0       157            157
158      0       158            158

[159 rows x 3 columns]

In [31]:
combos = e0['unique_trk_id'].reset_index().merge(
        e0['unique_trk_id'].reset_index(), on='entry', suffixes=('_1', '_2'))
connections = combos[combos['unique_trk_id_1']!= combos['unique_trk_id_2']][['unique_trk_id_1', 'unique_trk_id_2']]

In [37]:
connections.values

array([[  0,   1],
       [  0,   2],
       [  0,   3],
       ...,
       [158, 155],
       [158, 156],
       [158, 157]])

In [53]:
d = np.load('/home/lhv14/Lucas/built_graphs/graph_0.npz', mmap_mode='r')

In [56]:
for k in d.files:
     name = k

In [58]:
d[name]

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4497/984513809.py", line 1, in <cell line: 1>
    d[name]
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/numpy/lib/npyio.py", line 254, in __getitem__
    return format.read_array(bytes,
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/numpy/lib/format.py", line 743, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 317, in executing
    args = executing_cache[key]
KeyError: (<code object run_code at 0x7f6c16885920, file "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3333>, 140102211229984, 74)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 799, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 854, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 565, in stack_data
    yield from collapse_repeated(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/utils.py", line 84, in collapse_repeated
    yield from map(mapper, original_group)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 555, in mapper
    return cls(f, options)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 520, in __init__
    self.executing = Source.executing(frame_or_tb)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 369, in executing
    args = find(source=cls.for_frame(frame), retry_cache=True)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 252, in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 270, in for_filename
    result = source_cache[filename] = cls._for_filename_and_lines(filename, lines)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 281, in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 81, in __init__
    self.asttokens()
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 413, in asttokens
    return ASTTokens(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/asttokens.py", line 65, in __init__
    self.mark_tokens(self._tree)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/asttokens.py", line 76, in mark_tokens
    MarkTokens(self).visit_tree(root_node)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 47, in visit_tree
    util.visit_tree(node, self._visit_before_children, self._visit_after_children)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/util.py", line 192, in visit_tree
    ret = postvisit(current, par_value, value)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 90, in _visit_after_children
    nfirst, nlast = self._methods.get(self, node.__class__)(node, first, last)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 268, in visit_keyword
    util.expect_token(name, token.NAME, node.arg)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/util.py", line 56, in expect_token
    raise ValueError("Expected token %s, got %s on line %s col %s" % (
ValueError: Expected token NAME:'help', got NAME:'ast_transformers' on line 253 col 5

# Node level prediction

In [11]:
Graph = namedtuple('Graph', ['x', 'y'])

In [15]:
feature_names = ['trk_pt', 'trk_eta', 'trk_phi', 'trk_d0', 'trk_z0']

#X = (trk[feature_names].values / feature_scale).astype(np.float32)
X = trk[feature_names].values
y = trk['is_pv'].values

In [16]:
class GNNModel(nn.Module):
    
    def __init__(self, c_in, c_hidden, c_out, num_layers=2, layer_name="GCN", dp_rate=0.1, **kwargs):
        """
        Inputs:
            c_in - Dimension of input features
            c_hidden - Dimension of hidden features
            c_out - Dimension of the output features. Usually number of classes in classification
            num_layers - Number of "hidden" graph layers
            layer_name - String of the graph layer to use
            dp_rate - Dropout rate to apply throughout the network
            kwargs - Additional arguments for the graph layer (e.g. number of heads for GAT)
        """
        super().__init__()
        gnn_layer = gnn_layer_by_name[layer_name]
        
        layers = []
        in_channels, out_channels = c_in, c_hidden
        for l_idx in range(num_layers-1):
            layers += [
                gnn_layer(in_channels=in_channels, 
                          out_channels=out_channels,
                          **kwargs),
                nn.ReLU(inplace=True),
                nn.Dropout(dp_rate)
            ]
            in_channels = c_hidden
        layers += [gnn_layer(in_channels=in_channels, 
                             out_channels=c_out,
                             **kwargs)]
        self.layers = nn.ModuleList(layers)
    
    def forward(self, x, edge_index):
        """
        Inputs:
            x - Input features per node
            edge_index - List of vertex index pairs representing the edges in the graph (PyTorch geometric notation)
        """
        for l in self.layers:
            # For graph layers, we need to add the "edge_index" tensor as additional input
            # All PyTorch Geometric graph layer inherit the class "MessagePassing", hence
            # we can simply check the class type.
            if isinstance(l, geom_nn.MessagePassing):
                x = l(x, edge_index)
            else:
                x = l(x)
        return x

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_165195/1323351676.py", line 1, in <cell line: 1>
    class GNNModel(nn.Module):
NameError: name 'nn' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 317, in executing
    args = executing_cache[key]
KeyError: (<code object run_code at 0x7f229ed9d920, file "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3333>, 139786670692640, 74)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 799, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/IPython/core/ultratb.py", line 854, in get_records
    return list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 565, in stack_data
    yield from collapse_repeated(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/utils.py", line 84, in collapse_repeated
    yield from map(mapper, original_group)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 555, in mapper
    return cls(f, options)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 520, in __init__
    self.executing = Source.executing(frame_or_tb)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 369, in executing
    args = find(source=cls.for_frame(frame), retry_cache=True)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 252, in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 270, in for_filename
    result = source_cache[filename] = cls._for_filename_and_lines(filename, lines)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 281, in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/stack_data/core.py", line 81, in __init__
    self.asttokens()
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/executing/executing.py", line 413, in asttokens
    return ASTTokens(
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/asttokens.py", line 65, in __init__
    self.mark_tokens(self._tree)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/asttokens.py", line 76, in mark_tokens
    MarkTokens(self).visit_tree(root_node)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 47, in visit_tree
    util.visit_tree(node, self._visit_before_children, self._visit_after_children)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/util.py", line 192, in visit_tree
    ret = postvisit(current, par_value, value)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 90, in _visit_after_children
    nfirst, nlast = self._methods.get(self, node.__class__)(node, first, last)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/mark_tokens.py", line 268, in visit_keyword
    util.expect_token(name, token.NAME, node.arg)
  File "/home/lhv14/anaconda3/envs/icenet/lib/python3.9/site-packages/asttokens/util.py", line 56, in expect_token
    raise ValueError("Expected token %s, got %s on line %s col %s" % (
ValueError: Expected token NAME:'help', got NAME:'ast_transformers' on line 253 col 5